use nec;
select * from ilog

select * from INVENTORY_PART_TAB
select * from INVENTORY_TRANSACTION_HIST_TAB
select * from N_AIS_SHOP_LIST_PICKED_ACT_TAB order by CONTRACT,N_SHOP_LIST_ID,PART_NO,LOT_BATCH_NO
select * from N_TRANSPORT_ORDER_TAB order by CONTRACT,N_TRANSPORT_ORDER_NO
select * from SHOP_ORD_TAB 
select * from SHOP_ORDER_OPERATION_TAB

--select * from INVENTORY_PART_TAB where HAZARD_CODE<>null

--select count(distinct(N_SHOP_LIST_ID)) from N_AIS_SHOP_LIST_PICKED_ACT_TAB
--select count(distinct(N_TRANSPORT_ORDER_NO))  from N_TRANSPORT_ORDER_TAB

--delete INVENTORY_PART_TAB
--delete INVENTORY_TRANSACTION_HIST_TAB
--delete N_AIS_SHOP_LIST_PICKED_ACT_TAB 
--delete N_TRANSPORT_ORDER_TAB
--delete SHOP_ORD_TAB
--delete SHOP_ORDER_OPERATION_TAB
--delete ilog

--drop table INVENTORY_PART_TAB
--drop table INVENTORY_TRANSACTION_HIST_TAB
--drop table N_AIS_SHOP_LIST_PICKED_ACT_TAB
--drop table N_TRANSPORT_ORDER_TAB
--drop table SHOP_ORD_TAB
--drop table SHOP_ORDER_OPERATION_TAB

