CREATE TABLE INVENTORY_PART_TAB
(
	PART_NO VARCHAR2(25),
	CONTRACT VARCHAR2(5),
	ASSET_CLASS VARCHAR2(2),
	ACCOUNTING_GROUP VARCHAR2(5),
	PRIME_COMMODITY VARCHAR2(5),
	N_OBL_PART_TYPE VARCHAR2(32),
	LAST_ACTIVITY_DATE date
);
CREATE TABLE INVENTORY_TRANSACTION_HIST_TAB
(
	TRANSACTION_ID NUMBER primary key,
	ACCOUNTING_ID NUMBER,
	PART_NO VARCHAR2(25),
	CONTRACT VARCHAR2(5),
	DATE_APPLIED date,
	EXPIRATION_DATE date
);
CREATE TABLE N_AIS_SHOP_LIST_PICKED_ACT_TAB
(
	"N_SEQ_NO" NUMBER primary key,
	"CONTRACT" VARCHAR2(5 BYTE), 
	"N_SHOP_LIST_ID" VARCHAR2(14 BYTE), 
	"PART_NO" VARCHAR2(25 BYTE), 
	"LOT_BATCH_NO" VARCHAR2(20 BYTE), 
	"WORK_CENTER_NO" VARCHAR2(5 BYTE), 
	"ENG_CHG_LEVEL" VARCHAR2(6 BYTE), 
	"LOCATION_NO" VARCHAR2(35 BYTE), 
	"N_PICKED_DATE" DATE, 
	"N_QTY_PICKED" NUMBER, 
	"N_Z_AXIS" VARCHAR2(10 BYTE), 
	"N_POSITION" VARCHAR2(10 BYTE), 
	"N_CREATED_DATE" DATE, 
	"N_CREATED_USER" VARCHAR2(30 BYTE), 
	"N_UPDATED_DATE" DATE NOT NULL ENABLE, 
	"N_UPDATED_USER" VARCHAR2(30 BYTE), 
	"ROWVERSION" DATE, 
	"ROWKEY" VARCHAR2(50 BYTE)
);
CREATE TABLE N_TRANSPORT_ORDER_TAB
(
	CONTRACT VARCHAR2(5),
	N_TRANSPORT_ORDER_NO VARCHAR2(19),
	N_TRANSPORT_TYPE NUMBER,
	N_TRANSPORT_DATE date
);
CREATE TABLE SHOP_ORD_TAB
(
	ORDER_NO VARCHAR2(12),
	RELEASE_NO VARCHAR2(4),
	SEQUENCE_NO VARCHAR2(4),
	ORG_START_DATE date,
	CONTRACT VARCHAR2(5)
);
CREATE TABLE SHOP_ORDER_OPERATION_TAB
(
	ORDER_NO VARCHAR2(12),
	RELEASE_NO VARCHAR2(4),
	SEQUENCE_NO VARCHAR2(4),
	OPERATION_NO  NUMBER,
	
	ROWVERSION  date,
	ROWKEY VARCHAR2(50)
);
CREATE TABLE SHOP_MATERIAL_ALLOC_TAB
(
	ORDER_NO VARCHAR2(12),
	RELEASE_NO VARCHAR2(4),
	SEQUENCE_NO VARCHAR2(4),
	LINE_ITEM_NO  NUMBER,
	
	ROWVERSION  date,
	ROWKEY VARCHAR2(50)
);